---
webroot: /var/www
fileroot: /var/files
docroot: docroot
apache_server_admin: eduardo.esclapes@gmail.com
sites:
  dev:
    fqdn: v3.opcions.org
    repo: git@bitbucket.org:esclapes/opcions.org.git
    db_name: v3_opcions
    db_user: v3_opcions
    db_pass: v3_0pcion5
  localtest:
    fqdn: localtest.opcions.org
    repo: git@bitbucket.org:esclapes/opcions.org.git
    db_name: testopcions
    db_user: testopcions
    db_pass: test0pcion5
